name: Pull Request

on:
  pull_request:

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run ci
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
