name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm ci
      - run: npm run semantic-release
      - run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
